package com.epam.poc.entity;

import com.vladmihalcea.hibernate.type.json.JsonType;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;

import javax.persistence.*;
import java.util.HashMap;
import java.util.Map;

@Entity
@Table(name = "usersettings")
@TypeDef(name = "json", typeClass = JsonType.class)
@Getter @Setter
public class UserSettings {

    @Id
    @GeneratedValue( strategy = GenerationType.SEQUENCE, generator = "ISEQ$$_73154") // ISEQ$$_73154 auto generated by liquibase, not sure how to automate it
    private Long id;

    //@Column(name = "userid")
    private Integer userId;

    //@Column(name = "devicetype")
    private String deviceType;

    @Type(type = "json")
    @Column(columnDefinition = "jsonb")
    private Map<String, String> content = new HashMap<>();

}